#!bash

export BASE_URL=https://keycloak.zenika.lan
export CLIENT_ID=myapp1
export REALM=bzhcamp

REFRESH_TOKEN="eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJiZTQ4MmE5Yi1mZWU0LTQ1Y2EtYjcxYi01ODlkYTI4YjUxYWIifQ.eyJleHAiOjE3ODIzMTk4ODIsImlhdCI6MTc4MjMxODA4MiwianRpIjoiYzA2ZmMyMTMtM2Q4Zi0xNWI3LTEyNWItZThiN2FiOGI4NmFkIiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay56ZW5pa2EubGFuL3JlYWxtcy9iemhjYW1wIiwiYXVkIjoiaHR0cHM6Ly9rZXljbG9hay56ZW5pa2EubGFuL3JlYWxtcy9iemhjYW1wIiwic3ViIjoiZTU0ZmY0MDYtZDAyMS00OTMxLTk0NjItYjRlYzQ3YTg3Mjc4IiwidHlwIjoiUmVmcmVzaCIsImF6cCI6Im15YXBwMiIsInNpZCI6Im9Dc0tHQVJXalR6OUlhcm56aVRqZFZKTSIsImNuZiI6eyJqa3QiOiJJS1hLbVFTdUxvN0NVQUFTY3dLMnhTc3lkR0VPcVFqZWpxSzNCaUh6UkEwIn0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgYWNyIGVtYWlsIHJvbGVzIGJhc2ljIiwicmV1c2VfaWQiOiJhYzE5MjE4YS0yNTc5LTRiODItYWY0YS02Y2I4MzY0NDI3MzUifQ.ahEjezZcb9BemLPzUS8LESVCzXCrJ9MDVJgecOgk_yVU-R9VJZhJ9kqvOycHkr1sht8--1aHpYscanccBVjShQ"

curl -d "client_id=$CLIENT_ID" \
     -d "grant_type=refresh_token" \
     -d "refresh_token=$REFRESH_TOKEN" \
     "$BASE_URL/realms/$REALM/protocol/openid-connect/token" | jq